[logger]
    mode = "debug"
    timestamp = "time"

[authorization]
    [[authorization.users]]
        username = "username"
        password = "password"

[api]
    enable = true
    auth = false
    env = "development"

[catalog]
    path = "catalog"
    update_interval = 10